# Generated by Django 4.2 on 2023-05-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffRegistration', '0002_restuarant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restuarant',
            name='add',
            field=models.CharField(max_length=150),
        ),
    ]
