# Generated by Django 4.2 on 2023-05-09 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='add',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='add_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='phone_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
