# Generated by Django 4.2 on 2023-05-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_booking_add_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='add',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
